In [1]:
import numpy as np
a=[1,2,3,4]
b=np.array(a)
print(b)

[1 2 3 4]


In [2]:
print(type(b))

<class 'numpy.ndarray'>


In [4]:
a=[1,2,3,4,5.6,"Hello",True]
b=np.array(a)
print(b)

ValueError: invalid literal for int() with base 10: 'Hello'

In [7]:
b=np.ones((2,3),dtype=int)

In [8]:
b

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
b=np.empty((5,2),dtype=int)

In [15]:
b

array([[  567983776,         378],
       [  603304272,         378],
       [          0,           0],
       [-2147483648,       32767],
       [          0,           0]])

In [22]:
b=np.linspace(2,10,5,endpoint=False)

In [23]:
b

array([2. , 3.6, 5.2, 6.8, 8.4])

In [24]:
b=np.random.randint(2,12,6)
b

array([11,  6,  8,  9,  4,  3])

In [1]:
arr_2d=[[1,2,3],[4,5,6]]

In [2]:
import numpy as np
print(np.array(arr_2d))

[[1 2 3]
 [4 5 6]]


In [4]:
print(arr_2d[1][1])
print(np.array(arr_2d)[1][1])
print(np.array(arr_2d)[1,1])

5
5
5


In [4]:
import numpy as np
import csv
with open("C:\\Users\\Soumyansh\\Desktop\\terrorismData.csv",encoding="utf8") as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    file_list=list(file_data)
killed=[]
country=[]
for row in file_list:
    
    killed.append(row['Killed'])
    country.append(row['Country'])

np_killed=np.array(killed)
np_country=np.array(country)
np_killed[np_killed=='']='0.0'
print(np_killed)
np_killed=np.array(np_killed,dtype=float)
np_country=np.array(country)
killed_USA=np_killed[np_country=='United States']
print(int(np.sum(killed_USA)))

['1.0' '0.0' '1.0' ... '0.0' '0.0' '0.0']
3771


In [19]:
import numpy as np
import csv
file_obj=open("C:\\Users\\Soumyansh\\Desktop\\terrorismData.csv",encoding="utf8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)
year=[]
day=[]
month=[]
for row in file_data:
    day.append(row['Day'])
    year.append(row['Year'])
    month.append(row['Month'])
    
np_day=np.array(day,dtype=float)
np_month=np.array(month,dtype=float)
np_year=np.array(year,dtype=float)

bool_arr1=((np_day>=1) & (np_day<=31))

bool_arr2=np_month==1

bool_arr3=np_year==2010

final_arr=(bool_arr1) & (bool_arr2) & (bool_arr3)
ans=np_day[final_arr]
count=0
for i in ans:
    count=count+1
print(count)

271


In [20]:
#month year city nameofgroup killed wounded
import numpy as np
import csv
file_obj=open("C:\\Users\\Soumyansh\\Desktop\\terrorismData.csv",encoding="utf8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)
year=[]
day=[]
month=[]
for row in file_data:
    day.append(row['Day'])
    year.append(row['Year'])
    month.append(row['Month'])
    
np_day=np.array(day,dtype=float)
np_month=np.array(month,dtype=float)
np_year=np.array(year,dtype=float)

bool_arr1=((np_day>=1) & (np_day<=31))

bool_arr2=np_month==1

bool_arr3=np_year==2010

final_arr=(bool_arr1) & (bool_arr2) & (bool_arr3)
ans=np_day[final_arr]
count=0
for i in ans:
    count=count+1
print(count)

271


In [21]:
print(90, end=' ')
print('Shiliguri',end=' ')
print('United Liberation Front of Assam (ULFA)')

90 Shiliguri United Liberation Front of Assam (ULFA)


In [71]:
#month year city nameofgroup killed wounded
import numpy as np
import csv
file_obj=open("C:\\Users\\Soumyansh\\Desktop\\terrorismData.csv",encoding="utf8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)
year=[]
month=[]
state=[]
killed=[]
wounded=[]
final=[]
#Making lists
for row in file_data:    
    year.append(row['Year'])
    month.append(row['Month'])
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    state.append(row['State'])
    final.append([row['Killed'],row['Wounded'],row['City'],row['Group']])
#Making numpy arrays out of lits
np_month=np.array(month)
np_year=np.array(year)
np_killed=np.array(killed)
np_state=np.array(state)
np_wounded=np.array(wounded)
np_final=np.array(final)

#fixing values
np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'

#Conversions to float
np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)
np_month=np.array(np_month,dtype=float)
np_year=np.array(np_year,dtype=float)

#Making boolean conditionals
bool_arr1=((np_month>=5) & (np_month<=7))
bool_arr2=np_year==1999
bool_arr3=np_state=='Jammu and Kashmir'
final_bool=bool_arr1 & bool_arr2 & bool_arr3
np_final=np_final[final_bool]

for i in range(len(np_final)):
    for j in range(len(np_final[0])):
        if np_final[i][j]=='':
            np_final[i][j]='0.0'


max=0.0
for i in range(len(np_final)):
    casualities=float(np_final[i,0])+float(np_final[i,1])
    
    if casualities>max:
        max=casualities
        temp=i
print(str(int(max))," "+np_final[temp,2]+" "+np_final[temp,3])

22  Kargil District Separatists


In [73]:
#month year city nameofgroup killed wounded
import numpy as np
import csv
file_obj=open("C:\\Users\\Soumyansh\\Desktop\\terrorismData.csv",encoding="utf8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)
state=[]
killed=[]
wounded=[]
#Making lists
for row in file_data:    
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    state.append(row['State'])
    
#Making numpy arrays out of lits
np_killed=np.array(killed)
np_state=np.array(state)
np_wounded=np.array(wounded)

#fixing values
np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'

#Conversions to float
np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)
#Making boolean conditionals
bool_arr1=((np_state=='Andhra Pradesh') | (np_state=='Jharkhand') | (np_state=='Odisha') | (np_state=='Chhattisgarh'))

np_final=np_killed+np_wounded
np_final=np_final[bool_arr1]
ans=np.sum(np_final)
print(int(ans))

5628


In [77]:
import csv
with open("C:\\Users\\Soumyansh\\Desktop\\terrorismData.csv",encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    file_list=list(file_data)
d={}
for row in file_list:
    key=row['Day']
    d[key]=d.get(key,0)+1

max=0
for i in d:
    if(d[i]>max):
        max=d[i]
        temp=i
print(temp+" ",max)

15  6500


In [1]:
#month year city nameofgroup killed wounded
import numpy as np
import csv
file_obj=open("C:\\Users\\Soumyansh\\Desktop\\A.csv",encoding="utf8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)
country=[]
killed=[]
wounded=[]
city=[]
final=[]
#Making lists
for row in file_data:    
    city.append(row['City'])
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])
    final.append([row['City'],row['Killed'],row['Wounded'],row['Country']])
#Making numpy arrays out of lits
np_city=np.array(city)
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_country=np.array(country)
np_final=np.array(final)

#fixing values
np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'

#Conversions to float
np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)
np_casualities=np_killed+np_wounded
#Making boolean conditionals
bool_arr=((np_country=='India'))

np_final=np_final[bool_arr]

for i in range(len(np_final)):
    for j in range(len(np_final[0])):
        if np_final[i][j]=='':
            np_final[i][j]='0.0'

print(np_final)            
for i in range(len(np_final)):
    np_final[i,1]=int(float(np_final[i,1])+float(np_final[i,2]))

np_final=np_final[0:5,0:2]
for i in range(len(np_final)):
    for j in range(len(np_final[0])):
        print(np_final[i][j],end=' ')
    print()

# np_final=np_final[np_final[:1].argsort()]
# print(np_final)

[['Mumbai' '188' '817' 'India']
 ['Mumbai' '52' '150' 'India']
 ['Mumbai' '68' '76' 'India']
 ['Mumbai' '58' '76' 'India']
 ['Mumbai' '9' '76' 'India']
 ['Mumbai' '11' '64' 'India']
 ['Mumbai' '32' '22' 'India']
 ['Mumbai' '8' '44' 'India']
 ['Mumbai' '9' '43' 'India']
 ['Mumbai' '9' '43' 'India']
 ['Mumbai' '2' '36' 'India']
 ['Mumbai' '5' '31' 'India']
 ['Mumbai' '0' '27' 'India']
 ['Mumbai' '1' '13' 'India']
 ['Mumbai' '0' '9' 'India']
 ['Mumbai' '9' '0' 'India']
 ['Mumbai' '2' '5' 'India']
 ['Mumbai' '4' '2' 'India']
 ['Mumbai' '3' '0' 'India']
 ['Mumbai' '1' '1' 'India']
 ['Mumbai' '1' '1' 'India']
 ['Mumbai' '1' '1' 'India']
 ['Mumbai' '0' '2' 'India']
 ['Mumbai' '1' '0' 'India']
 ['Mumbai' '0' '1' 'India']
 ['Mumbai' '0' '1' 'India']
 ['Mumbai' '0' '1' 'India']
 ['Mumbai' '0' '0' 'India']]
Mumbai 1005 
Mumbai 202 
Mumbai 144 
Mumbai 134 
Mumbai 85 


In [2]:
import csv
import operator
with open("C:\\Users\\Soumyansh\\Desktop\\terrorismData.csv",encoding="utf8") as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    file_list=list(file_data)
d={}
temp1=0.0
temp2=0.0
for row in file_list:
    key=row['Country']
    if 'India' in key:
        
        key=row['City']
        if key!='Unknown':
            temp1=row['Killed']
            temp2=row['Wounded']
            if temp1=='' and temp2=='':
                temp1=0.0
                temp2=0.0
            elif temp1=='':
                temp1=0.0
                temp2=float(temp2)
            elif temp2=='':
                temp2=0.0
                temp1=float(temp1)
            else:
                temp1=float(temp1)
                temp2=float(temp2)
            value=temp1+temp2
            if key in d:
                d[key]=d[key]+value
            else:
                d[key]=value
sorted_d = sorted((value, key) for (key,value) in d.items())
l=sorted_d[-5:]

for i in reversed(l):
    value,key=i
    print(key+" ",int(value))
    

Srinagar  3134
New Delhi  2095
Mumbai  2016
Jammu  1119
Guwahati  822


In [16]:
import numpy as np
import csv
import operator
with open("C:\\Users\\Soumyansh\\Desktop\\terrorismData.csv",encoding="utf8") as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    file_list=list(file_data)
Country=[]
City=[]
Killed=[]
Wounded=[]
Final=[]
for row in file_list:
    Country.append(row['Country'])
    City.append(row['City'])
    Killed.append(row['Killed'])
    Wounded.append(row['Wounded'])
    Final.append([row['City'],row['Killed'],row['Wounded']])
#Making numpy arrays        
np_country=np.array(Country)
bool_arr=np_country=='India'
np_city=np.array(City)
np_killed=np.array(Killed)
np_wounded=np.array(Wounded)
np_final=np.array(Final)
#Fixing values
np_final=np_final[bool_arr]

np_final[np_final[:,1]=='']='0.0'
np_final[np_final[:,2]=='']='0.0'

print(np_final[1:5,:3])

[['Aatpal' '1' '0']
 ['0.0' '0.0' '0.0']
 ['Abhayapuri' '1' '1']
 ['Abhoynagar' '0' '2']]


In [1]:
import numpy as np
import csv
file_obj=open("C:\\Users\\Soumyansh\\Desktop\\terrorismData.csv",encoding="utf8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)
country=[]
killed=[]
wounded=[]
city=[]
final=[]

#Making lists
for row in file_data:
    if row['Country']=='India':
        country.append(row['Country'])
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        city.append(row['City'])
        final.append([row['City'],row['Killed'],row['Wounded']])


#Making numpy arrays out of lists
np_month=np.array(country)
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_city=np.array(city)
np_final=np.array(final)


#Fixing blank values in final arr
np_final[np_final=='']='0.0'

print(np_final[0:5,:])

[['Aankro' '3' '0']
 ['Aatpal' '1' '0']
 ['Abhapalli' '5' '0.0']
 ['Abhayapuri' '1' '1']
 ['Abhoynagar' '0' '2']]
