## Numpy - Arrays

#### Numpy - Arrays declaration

In [1]:
import numpy as np

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [11]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [13]:
np.zeros(5) + 2

array([ 2.,  2.,  2.,  2.,  2.])

In [17]:
np.repeat(2, 5)

array([2, 2, 2, 2, 2])

In [21]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [23]:
np.linspace(0, 2018, 10)

array([    0.        ,   224.22222222,   448.44444444,   672.66666667,
         896.88888889,  1121.11111111,  1345.33333333,  1569.55555556,
        1793.77777778,  2018.        ])