## Numpy - Arrays

#### Numpy - Arrays declaration

In [2]:
import numpy as np

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.zeros(5) + 2

array([2., 2., 2., 2., 2.])

In [6]:
np.repeat(2,5)

array([2, 2, 2, 2, 2])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(0,2019,10)

array([   0.        ,  224.33333333,  448.66666667,  673.        ,
        897.33333333, 1121.66666667, 1346.        , 1570.33333333,
       1794.66666667, 2019.        ])